"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
osc99 = true
version = 2

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#23e976"
  style = "plain"
  template = "{{.Icon}}  "
  type = "os"

  [[blocks.segments]]
  foreground = "#E5C07B"
  style = "plain"
  template = "[{{ .CurrentDate | date .Format }}]"
  type = "time"

    [blocks.segments.properties]
    time_format = "15:04"

  [[blocks.segments]]
  type = "shell"
  style = "plain"
  foreground = "#d6e06c"
  template = "  {{ .Name }}"

[blocks.segments.properties.mapped_shell_names]
pwsh = "Shell"
powershell = "Shell"
cmd = "Cmd"
bash = "Bash"

  [[blocks.segments]]
  foreground = "#F3C267"
  foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}",
  "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
  "{{ if gt .Behind 0 }}#B388FF{{ end }}"
]
  style = "plain"
  template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
  type = "git"

    [blocks.segments.properties]
    branch_max_length = 25
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = true

[[blocks]]
alignment = "right"
type = "prompt"

  [[blocks.segments]]
  type = "exit"
  style = "plain"
  foreground = "#b8ff75"
  foreground_templates = [ "{{ if gt .Code 0 }}#E06C75{{ end }}" ]
  template = " x{{ .Meaning }}"

  [[blocks.segments]]
  foreground = "#b8ff75"
  foreground_templates = [ "{{ if gt .Code 0 }}#E06C75{{ end }}" ]
  style = "diamond"
  template = " {{ .FormattedMs }} "
  type = "executiontime"

    [blocks.segments.properties]
    style = "roundrock"
    always_enabled = true

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#61AFEF"
  style = "plain"
  template = " {{ .Path }}"
  type = "path"

    [blocks.segments.properties]
    style = "full"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#E06C75"
  style = "plain"
  template = "!"
  type = "root"

  [[blocks.segments]]
  foreground = "#ffffff"
  style = "plain"
  template = "<#CB4B16>❯</><#CACA02>❯</><#4E9A06>❯</>"
  type = "text"

[transient_prompt]
background = "transparent"
foreground = "#FEF5ED"
template = " "

[secondary_prompt]
background = "transparent"
foreground = "#D6DEEB"
template = "<#CB4B16>❯</><#CACA02>❯</><#4E9A06>❯</>"
